// <auto-generated />
using System;
using Backend_Taller.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_Taller.Migrations
{
    [DbContext(typeof(TallerDbContext))]
    [Migration("20260927071420_User_Table_Modificada")]
    partial class User_Table_Modificada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend_Taller.Models.Clientes", b =>
                {
                    b.Property<int>("ClientesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientesId"));

                    b.Property<string>("Cp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RfcFisico")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ClientesId");

                    b.HasIndex("Nombre");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Backend_Taller.Models.Iva", b =>
                {
                    b.Property<int>("IvaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IvaId"));

                    b.Property<decimal>("IvaValue")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("IvaId");

                    b.ToTable("Iva");
                });

            modelBuilder.Entity("Backend_Taller.Models.Marcas", b =>
                {
                    b.Property<int>("MarcasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcasId"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MarcasId");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Backend_Taller.Models.OrdenServicio", b =>
                {
                    b.Property<int>("OrdenServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenServicioId"));

                    b.Property<int>("ClientesId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kilometraje")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RfcMoralId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculosId")
                        .HasColumnType("int");

                    b.HasKey("OrdenServicioId");

                    b.HasIndex("ClientesId");

                    b.HasIndex("RfcMoralId");

                    b.HasIndex("VehiculosId");

                    b.ToTable("OrdenesServicio");
                });

            modelBuilder.Entity("Backend_Taller.Models.Presupuestos", b =>
                {
                    b.Property<int>("PresupuestosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PresupuestosId"));

                    b.Property<decimal>("Anticipo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CargosAdicionales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ManoObra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.Property<decimal>("OtrosMateriales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Refacciones")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Resta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Seguro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PresupuestosId");

                    b.HasIndex("OrdenServicioId")
                        .IsUnique();

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Backend_Taller.Models.RfcMoral", b =>
                {
                    b.Property<int>("RfcMoralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RfcMoralId"));

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RfcMoralValue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RfcMoralId");

                    b.HasIndex("Institucion");

                    b.ToTable("RfcMorales");
                });

            modelBuilder.Entity("Backend_Taller.Models.Servicios", b =>
                {
                    b.Property<int>("ServiciosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiciosId"));

                    b.Property<int?>("Clave")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("OrdenServicioId")
                        .HasColumnType("int");

                    b.HasKey("ServiciosId");

                    b.HasIndex("OrdenServicioId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Backend_Taller.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Backend_Taller.Models.Vehiculos", b =>
                {
                    b.Property<int>("VehiculosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculosId"));

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MarcasId")
                        .HasColumnType("int");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroMotor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Placas")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehiculosId");

                    b.HasIndex("MarcasId");

                    b.HasIndex("Placas");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Backend_Taller.Models.OrdenServicio", b =>
                {
                    b.HasOne("Backend_Taller.Models.Clientes", "Cliente")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("ClientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend_Taller.Models.RfcMoral", "RfcMoral")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("RfcMoralId");

                    b.HasOne("Backend_Taller.Models.Vehiculos", "Vehiculo")
                        .WithMany("OrdenesServicio")
                        .HasForeignKey("VehiculosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("RfcMoral");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("Backend_Taller.Models.Presupuestos", b =>
                {
                    b.HasOne("Backend_Taller.Models.OrdenServicio", "OrdenServicio")
                        .WithOne("Presupuesto")
                        .HasForeignKey("Backend_Taller.Models.Presupuestos", "OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Backend_Taller.Models.Servicios", b =>
                {
                    b.HasOne("Backend_Taller.Models.OrdenServicio", "OrdenServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenServicio");
                });

            modelBuilder.Entity("Backend_Taller.Models.Vehiculos", b =>
                {
                    b.HasOne("Backend_Taller.Models.Marcas", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Backend_Taller.Models.Clientes", b =>
                {
                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("Backend_Taller.Models.Marcas", b =>
                {
                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Backend_Taller.Models.OrdenServicio", b =>
                {
                    b.Navigation("Presupuesto")
                        .IsRequired();

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Backend_Taller.Models.RfcMoral", b =>
                {
                    b.Navigation("OrdenesServicio");
                });

            modelBuilder.Entity("Backend_Taller.Models.Vehiculos", b =>
                {
                    b.Navigation("OrdenesServicio");
                });
#pragma warning restore 612, 618
        }
    }
}
